// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApi.Models;

#nullable disable

namespace ServerWebApi.Migrations.Recipe
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Ingredient.Model.IngredientItem", b =>
                {
                    b.Property<int>("IngredientItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientItemId");

                    b.ToTable("IngredientItem");
                });

            modelBuilder.Entity("RecipeApi.Models.RecipeItem", b =>
                {
                    b.Property<int>("RecipeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int?>("IngredientItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeItemId");

                    b.HasIndex("IngredientItemId");

                    b.ToTable("RecipeItems");
                });

            modelBuilder.Entity("RecipeApi.Models.RecipeItem", b =>
                {
                    b.HasOne("Ingredient.Model.IngredientItem", "IngredientItem")
                        .WithMany()
                        .HasForeignKey("IngredientItemId");

                    b.Navigation("IngredientItem");
                });
#pragma warning restore 612, 618
        }
    }
}
